# Araba Fiyatları (Car Prices)

🎯 Bu challenge’ın amacı, bir dataset hazırlamak ve şimdiye kadar öğrendiğiniz bazı feature selection tekniklerini uygulamaktır.

🚗 Arabalarla ilgili bir veri setiyle çalışıyoruz ve bir arabanın pahalı mı yoksa ucuz mu olduğunu tahmin etmek istiyoruz.

In [534]:
# Data manipulation
import numpy as np
import pandas as pd
# Data visualisation
import matplotlib.pyplot as plt
import seaborn as sns
# Sayısal bir özelliğin normal dağılım gösterip göstermediğini kontrol etme
from statsmodels.graphics.gofplots import qqplot

In [535]:
url = "https://d32aokrjazspmn.cloudfront.net/materials/ML_Cars_dataset.csv"

❓ CSV dosyasını `df` adlı bir veri çerçevesine yükleyin.

In [536]:
df = pd.read_csv(url)
df

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,std,front,64.1,2548,dohc,four,2.68,5000,expensive
1,std,front,64.1,2548,dohc,four,2.68,5000,expensive
2,std,front,65.5,2823,ohcv,six,3.47,5000,expensive
3,std,front,NaN,2337,ohc,four,3.40,5500,expensive
4,std,front,66.4,2824,ohc,five,3.40,5500,expensive
...,...,...,...,...,...,...,...,...,...
200,std,front,68.9,2952,ohc,four,3.15,5400,expensive
201,turbo,front,68.8,3049,ohc,four,3.15,5300,expensive
202,std,front,68.9,3012,ohcv,six,2.87,5500,expensive
203,turbo,front,68.9,3217,ohc,six,3.40,4800,expensive
204,turbo,front,68.9,3062,ohc,four,3.15,5400,expensive

ℹ️ Dataset’in açıklaması [burada](https://drive.google.com/file/d/1ADSyjWfRGYqdXwCCN4PPC7PjQeMZ-ap-/view?usp=sharing ) mevcuttur. Egzersiz boyunca buna mutlaka referans verin.

## (1) Yinelenenler (Duplicates)

❓ Varsa, veri kümesinden yinelenenleri kaldırın. ❓

*Veri çerçevesini `df`* üzerine yazın.

In [537]:
df.duplicated().sum()

14

In [538]:
df = df.drop_duplicates().reset_index(drop = True)
df

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,std,front,64.1,2548,dohc,four,2.68,5000,expensive
1,std,front,65.5,2823,ohcv,six,3.47,5000,expensive
2,std,front,NaN,2337,ohc,four,3.40,5500,expensive
3,std,front,66.4,2824,ohc,five,3.40,5500,expensive
4,std,front,66.3,2507,ohc,five,3.40,5500,expensive
...,...,...,...,...,...,...,...,...,...
186,std,front,68.9,2952,ohc,four,3.15,5400,expensive
187,turbo,front,68.8,3049,ohc,four,3.15,5300,expensive
188,std,front,68.9,3012,ohcv,six,2.87,5500,expensive
189,turbo,front,68.9,3217,ohc,six,3.40,4800,expensive
190,turbo,front,68.9,3062,ohc,four,3.15,5400,expensive

In [539]:
df.duplicated().sum()

0

## (2)  Eksik değerler (Missing values)

❓ Eksik değerleri bulun ve bunları ya `strategy = "most frequent"` (kategorik değişkenler için) ya da `strategy = "median"` (sayısal değişkenler için) kullanarak doldurun ❓

In [540]:
df.isnull().sum().sort_values(ascending=False)/len(df)

enginelocation    0.052356
carwidth          0.010471
aspiration        0.000000
curbweight        0.000000
enginetype        0.000000
cylindernumber    0.000000
stroke            0.000000
peakrpm           0.000000
price             0.000000
dtype: float64

### `carwidth`

<details>
    <summary> 💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>carwidth</code> sütununda eksik değerler birden fazla şekilde temsil edilmektedir. Bazıları <code>np.nan</code>, bazıları ise <code>*</code> olarak yer alır. Bunlar tespit edildikten sonra, eksik değerler verinin %30’undan daha azını oluşturduğu için medyan değerle doldurulabilir.
</details>

In [541]:
print(df.carwidth.value_counts(dropna=False))

carwidth
66.5    22
63.8    19
65.4    15
63.6     9
68.4     9
64       9
64.4     9
65.5     8
65.2     7
65.6     6
64.2     6
66.3     6
67.2     6
66.9     5
67.9     5
*        4
68.9     4
71.7     3
70.3     3
65.7     3
63.9     3
64.8     3
65       2
67.7     2
68.3     2
71.4     2
NaN      2
66.6     1
63.4     1
72.3     1
64.1     1
68       1
72       1
70.5     1
66.1     1
70.6     1
69.6     1
61.8     1
66       1
64.6     1
60.3     1
70.9     1
66.4     1
68.8     1
Name: count, dtype: int64

In [542]:
from sklearn.impute import SimpleImputer
df = df.replace("*", np.nan)

carwidth_imputer = SimpleImputer(strategy='mean')
carwidth_imputer.fit(df[['carwidth']])
df['carwidth'] = carwidth_imputer.transform(df[['carwidth']])
df

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,std,front,64.100000,2548,dohc,four,2.68,5000,expensive
1,std,front,65.500000,2823,ohcv,six,3.47,5000,expensive
2,std,front,65.976216,2337,ohc,four,3.40,5500,expensive
3,std,front,66.400000,2824,ohc,five,3.40,5500,expensive
4,std,front,66.300000,2507,ohc,five,3.40,5500,expensive
...,...,...,...,...,...,...,...,...,...
186,std,front,68.900000,2952,ohc,four,3.15,5400,expensive
187,turbo,front,68.800000,3049,ohc,four,3.15,5300,expensive
188,std,front,68.900000,3012,ohcv,six,2.87,5500,expensive
189,turbo,front,68.900000,3217,ohc,six,3.40,4800,expensive
190,turbo,front,68.900000,3062,ohc,four,3.15,5400,expensive

### `enginelocation`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>enginelocation</code> kategorik bir feature olduğundan ve kategorilerin büyük çoğunluğu <code>front</code> olduğu için, en sık görülen değerle doldurun.
</details>

In [543]:
print(df.enginelocation.unique())

['front' nan 'rear']

In [544]:
print(df.enginelocation.value_counts(dropna=False))

enginelocation
front    179
NaN       10
rear       2
Name: count, dtype: int64

In [545]:
engine_imputer = SimpleImputer(strategy="most_frequent")
engine_imputer.fit(df[['enginelocation']])
df[['enginelocation']] = engine_imputer.transform(df[['enginelocation']])

df.head()

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,std,front,64.100000,2548,dohc,four,2.68,5000,expensive
1,std,front,65.500000,2823,ohcv,six,3.47,5000,expensive
2,std,front,65.976216,2337,ohc,four,3.40,5500,expensive
3,std,front,66.400000,2824,ohc,five,3.40,5500,expensive
4,std,front,66.300000,2507,ohc,five,3.40,5500,expensive

In [546]:
print(df.enginelocation.value_counts(dropna=False))

enginelocation
front    189
rear       2
Name: count, dtype: int64

🧪 **Kodunu test et**

In [547]:
from nbresult import ChallengeResult

result = ChallengeResult('missing_values',
                         dataset = df)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/mert/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/mert/Sprint-16/S16D2-S-Data-car-prices/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_missing_values.py::TestMissing_values::test_carwidth PASSED         [ 50%]
test_missing_values.py::TestMissing_values::test_engine_location PASSED  [100%]

============================== 2 passed in 0.82s ===============================


💯 You can commit your code:

git add tests/missing_values.pickle

git commit -m 'Completed missing_values step'

git push origin master

## (3) Sayısal özelliklerin ölçeklendirilmesi (Scaling the numerical features)

In [548]:
# Hatırlatma olarak, DataFrame hakkında bazı bilgiler
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   aspiration      191 non-null    object
 1   enginelocation  191 non-null    object
 2   carwidth        191 non-null    float64
 3   curbweight      191 non-null    int64
 4   enginetype      191 non-null    object
 5   cylindernumber  191 non-null    object
 6   stroke          191 non-null    float64
 7   peakrpm         191 non-null    int64
 8   price           191 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 13.6+ KB

In [549]:
# Ve işte ölçeklendirmemiz gereken veri kümesinin sayısal özellikleri
numerical_features = df.select_dtypes(exclude=['object']).columns
numerical_features

Index(['carwidth', 'curbweight', 'stroke', 'peakrpm'], dtype='object')

❓ **Soru: Sayısal feature’ların ölçeklenmesi** ❓

Sayısal feature’ları aykırı değerler (outliers) ve dağılımları açısından inceleyin ve duruma göre aşağıdaki yöntemleri uygulayın:
- Robust Scaler
- Standard Scaler

Dönüştürülmüş değerlerle orijinal sütunları değiştirin.

### `peakrpm` , `carwidth` , & `stroke`

In [550]:
df.describe()

         carwidth   curbweight      stroke      peakrpm
count  191.000000   191.000000  191.000000   191.000000
mean    65.976216  2573.204188    3.259607  5113.089005
std      2.094624   525.724187    0.317996   471.879096
min     60.300000  1488.000000    2.070000  4150.000000
25%     64.200000  2190.500000    3.110000  4800.000000
50%     65.600000  2443.000000    3.290000  5100.000000
75%     66.900000  2964.500000    3.410000  5500.000000
max     72.300000  4066.000000    4.170000  6600.000000

<details>
    <summary>💡 <i>İpucu</i> </summary>

    
ℹ️ <code>peakrpm</code>, <code>carwidth</code> ve <code>stroke</code> normal dağılıma sahiptir ancak aynı zamanda bazı aykırı değerler (outlier) içerir. Bu nedenle `RobustScaler()` kullanılması tavsiye edilir.
</details>

In [551]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

cols = ['peakrpm', 'carwidth', 'stroke']

df[cols] = scaler.fit_transform(df[cols])
df.describe()

         carwidth   curbweight      stroke     peakrpm
count  191.000000   191.000000  191.000000  191.000000
mean     0.139339  2573.204188   -0.101309    0.018699
std      0.775787   525.724187    1.059986    0.674113
min     -1.962963  1488.000000   -4.066667   -1.357143
25%     -0.518519  2190.500000   -0.600000   -0.428571
50%      0.000000  2443.000000    0.000000    0.000000
75%      0.481481  2964.500000    0.400000    0.571429
max      2.481481  4066.000000    2.933333    2.142857

In [552]:
# SENİN KODUN BURAYA

### `curbweight`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>curbweight</code> normal bir dağılıma sahiptir ve aykırı değer (outlier) içermez. Bu nedenle Standard Scaler ile ölçeklenebilir.
</details>

In [553]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['curbweight']] = scaler.fit_transform(df[['curbweight']])
df

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,std,front,-0.555556,-0.048068,dohc,four,-2.033333,-0.142857,expensive
1,std,front,-0.037037,0.476395,ohcv,six,0.600000,-0.142857,expensive
2,std,front,0.139339,-0.450474,ohc,four,0.366667,0.571429,expensive
3,std,front,0.296296,0.478302,ohc,five,0.366667,0.571429,expensive
4,std,front,0.259259,-0.126260,ohc,five,0.366667,0.571429,expensive
...,...,...,...,...,...,...,...,...,...
186,std,front,1.222222,0.722416,ohc,four,-0.466667,0.428571,expensive
187,turbo,front,1.185185,0.907408,ohc,four,-0.466667,0.285714,expensive
188,std,front,1.222222,0.836844,ohcv,six,-1.400000,0.571429,expensive
189,turbo,front,1.222222,1.227807,ohc,six,0.366667,-0.428571,expensive
190,turbo,front,1.222222,0.932201,ohc,four,-0.466667,0.428571,expensive

🧪 **Kodunu test et**

In [554]:
from nbresult import ChallengeResult

result = ChallengeResult('scaling',
                         dataset = df
)

result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/mert/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/mert/Sprint-16/S16D2-S-Data-car-prices/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 4 items

test_scaling.py::TestScaling::test_carwidth PASSED                       [ 25%]
test_scaling.py::TestScaling::test_curbweight PASSED                     [ 50%]
test_scaling.py::TestScaling::test_peakrpm PASSED                        [ 75%]
test_scaling.py::TestScaling::test_stroke PASSED                         [100%]

============================== 4 passed in 0.68s ===============================


💯 You can commit your code:

git add tests/scaling.pickle

git commit -m 'Completed scaling step'

git push origin master

## (4) Kategorik özelliklerin kodlanması (Encoding the categorical features)

❓ **Soru: Kategorik değişkenlerin encode edilmesi** ❓

👇 Encode edilmesi gereken feature’ları inceleyin ve duruma göre aşağıdaki teknikleri uygulayın:

- One-hot encoding
- Manuel ordinal encoding

DataFrame içinde, orijinal feature’ları encode edilmiş versiyonlarıyla değiştirin.

### `aspiration` & `enginelocation`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>aspiration</code> ve <code>enginelocation</code> ikili (binary) kategorik feature’lardır.
</details>

In [555]:
print(f"The unique values of `aspiration` are {df.aspiration.unique()}") # Check unique values of `aspiration`

print(f"The unique values of `enginelocation` are {df.enginelocation.unique()}") # Check unique values of `enginelocation`\

print(f"The unique values of `enginelocation` are {df.cylindernumber.unique()}") # Check unique values of `enginelocation`\

The unique values of `aspiration` are ['std' 'turbo']
The unique values of `enginelocation` are ['front' 'rear']
The unique values of `enginelocation` are ['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']

In [556]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse_output=False,drop='if_binary')
df['aspiration'],df['enginelocation'] = encoder.fit_transform(df[['aspiration','enginelocation']]).T
df.head()

,aspiration,enginelocation,carwidth,curbweight,enginetype,cylindernumber,stroke,peakrpm,price
0,0.0,0.0,-0.555556,-0.048068,dohc,four,-2.033333,-0.142857,expensive
1,0.0,0.0,-0.037037,0.476395,ohcv,six,0.600000,-0.142857,expensive
2,0.0,0.0,0.139339,-0.450474,ohc,four,0.366667,0.571429,expensive
3,0.0,0.0,0.296296,0.478302,ohc,five,0.366667,0.571429,expensive
4,0.0,0.0,0.259259,-0.126260,ohc,five,0.366667,0.571429,expensive

### `enginetype`

<details>
    <summary>💡 <i>İpucu</i> </summary>
    <br>
    ℹ️ <code>enginetype</code> çok kategorili (multicategorical) bir feature’dır ve One-hot encoding uygulanmalıdır.
</details>

In [557]:
df.enginetype.unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object)

In [558]:
from sklearn.preprocessing import OneHotEncoder

# Instantiate a OneHotEncoder for the categorical feature EngineType
ohe = OneHotEncoder(sparse_output=False)

# Fitting it
ohe.fit(df[['enginetype']])

# Showing the categories detected by the encoder
display(ohe.categories_)

# Since Sklearn 1.1, we can retrieve the names of the generated columns
display(ohe.get_feature_names_out())

# Let's encode EngineType
enginetype_encoded = ohe.transform(df[['enginetype']])

# Now we store the encoded values in the dataframe
df[ohe.get_feature_names_out()] = enginetype_encoded

# We can get rid of the original column EngineType now
df.drop(columns='enginetype', inplace = True)

# And show df
df

[array(['dohc', 'dohcv', 'l', 'ohc', 'ohcf', 'ohcv', 'rotor'], dtype=object)]

array(['enginetype_dohc', 'enginetype_dohcv', 'enginetype_l',
       'enginetype_ohc', 'enginetype_ohcf', 'enginetype_ohcv',
       'enginetype_rotor'], dtype=object)

,aspiration,enginelocation,carwidth,curbweight,cylindernumber,stroke,peakrpm,price,enginetype_dohc,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,0.0,0.0,-0.555556,-0.048068,four,-2.033333,-0.142857,expensive,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,-0.037037,0.476395,six,0.600000,-0.142857,expensive,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.139339,-0.450474,four,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.296296,0.478302,five,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.259259,-0.126260,five,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,0.0,0.0,1.222222,0.722416,four,-0.466667,0.428571,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
187,1.0,0.0,1.185185,0.907408,four,-0.466667,0.285714,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
188,0.0,0.0,1.222222,0.836844,six,-1.400000,0.571429,expensive,0.0,0.0,0.0,0.0,0.0,1.0,0.0
189,1.0,0.0,1.222222,1.227807,six,0.366667,-0.428571,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
190,1.0,0.0,1.222222,0.932201,four,-0.466667,0.428571,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [559]:
df.shape

(191, 15)

### `cylindernumber`

<details>
    <summary>💡 İpucu </summary>

ℹ️ <code>cylindernumber</code> sıralı (ordinal) bir feature’dır ve sayısal değerlere manuel olarak encode edilmelidir.

</details>

In [560]:
df.cylindernumber.unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [561]:
mapping = {
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'eight': 8,
    'twelve': 12
}

df['cylindernumber'] = (
    df['cylindernumber']
    .astype(str)
    .str.strip()
    .str.lower()
    .map(mapping)
)
df[df['cylindernumber'].isna()]

Empty DataFrame
Columns: [aspiration, enginelocation, carwidth, curbweight, cylindernumber, stroke, peakrpm, price, enginetype_dohc, enginetype_dohcv, enginetype_l, enginetype_ohc, enginetype_ohcf, enginetype_ohcv, enginetype_rotor]
Index: []

❓ Artık `cylindernumber`’ı 2 ile 12 arasında sayısal bir feature’a dönüştürdüğünüze göre, bunu ölçeklendirmeniz gerekiyor ❓

<br/>

<details>
    <summary>💡 İpucu </summary>

`cylindernumber`’ın mevcut dağılımına bakın ve kendinize şu soruları sorun:
- Ölçekleme, bir feature’ın dağılımını etkiler mi?
- Bu feature’ın dağılımına göre en uygun ölçekleme yöntemi hangisidir?
</details>

In [562]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler

rb_scaler = RobustScaler()
rb = pd.DataFrame(rb_scaler.fit_transform(df[['cylindernumber']]))

mm_scaler = MinMaxScaler()
mm = pd.DataFrame(mm_scaler.fit_transform(df[['cylindernumber']]))

In [563]:
rb.value_counts()

0
 0.0    147
 2.0     23
 1.0     11
 4.0      5
-2.0      3
-1.0      1
 8.0      1
Name: count, dtype: int64

In [564]:
mm.value_counts()

0
0.2    147
0.4     23
0.3     11
0.6      5
0.0      3
0.1      1
1.0      1
Name: count, dtype: int64

In [565]:
from sklearn.preprocessing import RobustScaler

rb_scaler = RobustScaler()

df['cylindernumber'] = rb_scaler.fit_transform(df[['cylindernumber']])

df.head()

,aspiration,enginelocation,carwidth,curbweight,cylindernumber,stroke,peakrpm,price,enginetype_dohc,enginetype_dohcv,enginetype_l,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor
0,0.0,0.0,-0.555556,-0.048068,0.0,-2.033333,-0.142857,expensive,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,-0.037037,0.476395,2.0,0.600000,-0.142857,expensive,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.139339,-0.450474,0.0,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.296296,0.478302,1.0,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.259259,-0.126260,1.0,0.366667,0.571429,expensive,0.0,0.0,0.0,1.0,0.0,0.0,0.0

<details>
<summary><i>Ölçekleme ve encoding işlemlerinden sonra DataFrame’inizin nasıl görünmesi gerektiğine dair bir ekran görüntüsü aşağıdadır</i></summary>
    
    
<img src="https://wagon-public-datasets.s3.amazonaws.com/05-Machine-Learning/02-Prepare-the-dataset/car_price_after_scaling_and_encoding.png">    

</details>

### `price`

👇 Hedef `price`ı kodlayın.

<details>
    <summary>💡 İpucu </summary>
    <br>
    ℹ️ <code>price</code> target değişkendir ve LabelEncoder ile encode edilmelidir.
</details>

In [566]:
from sklearn.preprocessing import LabelEncoder

lb_encoder = LabelEncoder()
df['price'] = lb_encoder.fit_transform(df['price'])
df.price.value_counts()

price
1    97
0    94
Name: count, dtype: int64

🧪 **Kodunu test et**

In [567]:
from nbresult import ChallengeResult

result = ChallengeResult('encoding',
                         dataset = df)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/mert/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/mert/Sprint-16/S16D2-S-Data-car-prices/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 4 items

test_encoding.py::TestEncoding::test_aspiration PASSED                   [ 25%]
test_encoding.py::TestEncoding::test_enginelocation PASSED               [ 50%]
test_encoding.py::TestEncoding::test_enginetype PASSED                   [ 75%]
test_encoding.py::TestEncoding::test_price PASSED                        [100%]

============================== 4 passed in 0.56s ===============================


💯 You can commit your code:

git add tests/encoding.pickle

git commit -m 'Completed encoding step'

git push origin master

## (5) Temel Modelleme (Base Modelling)

👏 Veri kümesi ön işleme tabi tutuldu ve artık modele uyarlanmaya hazır.

❓ **Soru: Bir classification modelini ilk kez değerlendirme** ❓

Ön işlenmiş bu dataset üzerinde bir `LogisticRegression` modeli için cross-validation çalıştırın ve elde edilen skoru `base_model_score` adlı değişkende saklayın.

In [582]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

X = df.drop(columns=['price'])
y = df['price']

model = LogisticRegression()

score = cross_val_score(
    model,
    X,
    y,
    cv=10
)
base_model_score = score.mean()
base_model_score

0.8797368421052632

🧪 **Kodunu test et**

In [583]:
from nbresult import ChallengeResult

result = ChallengeResult('base_model',
                         score = base_model_score
)

result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/mert/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/mert/Sprint-16/S16D2-S-Data-car-prices/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_base_model.py::TestBase_model::test_base_model_score PASSED         [100%]

============================== 1 passed in 0.14s ===============================


💯 You can commit your code:

git add tests/base_model.pickle

git commit -m 'Completed base_model step'

git push origin master

## (6) Özellik Seçimi  (Feature Selection (with _Permutation Importance_))

👩🏻‍🏫 Bir feature’ın target’ı tahmin etmede gerçekten önemli olup olmadığını tespit etmenin güçlü bir yolu şudur:

1. Bir model çalıştırın ve skorunu ölçün  
2. Bu feature’ı karıştırın (shuffle edin), modeli tekrar çalıştırın ve skoru tekrar ölçün  
    - Eğer performans **belirgin şekilde düşerse**, bu feature önemlidir ve **çıkarılmamalıdır**
    - Eğer performans **çok fazla düşmezse**, bu feature **elenebilir**

❓ **Sorular** ❓

1. Modele en az bilgi katkısı sağlayan feature’ları tespit etmek için feature permutation uygulayın.
2. Model performansının belirgin şekilde düşmeye başladığını fark edene kadar zayıf feature’ları dataset’ten çıkarın.
3. Elde ettiğiniz yeni güçlü feature set’i ile yeni bir modeli cross-validation ile değerlendirin ve skorunu `strong_model_score` adlı değişkende saklayın.

In [607]:
import numpy as np
from sklearn.model_selection import cross_validate
from sklearn.inspection import permutation_importance

model = LogisticRegression()
cv_results = cross_validate(model, X, y, cv = 5)
score = cv_results["test_score"].mean()
#print(f"Before any feature permutation, the cross-validated accuracy is equal to {round(score,2)}")

model = LogisticRegression().fit(X,y)
perm_score = permutation_importance(
    model,
    X,
    y,
    n_repeats=100,
    random_state=42,
)
perm_score

{'importances_mean': array([8.27225131e-03, 5.23560209e-05, 1.12984293e-01, 2.87329843e-01,
        8.63874346e-03, 3.21989529e-02, 1.50785340e-02, 5.18324607e-03,
        0.00000000e+00, 0.00000000e+00, 1.50785340e-02, 1.87958115e-02,
        5.23560209e-04, 1.13089005e-02]),
 'importances_std': array([0.00726146, 0.00156981, 0.0201306 , 0.02633752, 0.00986116,
        0.01055919, 0.00954776, 0.00138422, 0.        , 0.        ,
        0.00835337, 0.00554554, 0.00157068, 0.00382736]),
 'importances': array([[0.0104712 , 0.02094241, 0.0104712 , ..., 0.0052356 , 0.0052356 ,
         0.0052356 ],
        [0.        , 0.        , 0.        , ..., 0.0052356 , 0.        ,
         0.        ],
        [0.14136126, 0.10471204, 0.09947644, ..., 0.10471204, 0.12041885,
         0.13089005],
        ...,
        [0.01570681, 0.01570681, 0.02617801, ..., 0.01570681, 0.0104712 ,
         0.03141361],
        [0.0052356 , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.0104712 , 0.01570681, 0.0052356 , ..., 0.01570681, 0.0104712 ,
         0.02094241]])}

In [613]:
importance_df = pd.DataFrame(np.vstack((X.columns,
                                        perm_score.importances_mean)).T, 
                            columns = ['feature','feature_importance'])

In [617]:
importance_df = importance_df.sort_values(by="feature_importance", ascending = False)  
importance_df

             feature feature_importance
3         curbweight            0.28733
2           carwidth           0.112984
5             stroke           0.032199
11   enginetype_ohcf           0.018796
10    enginetype_ohc           0.015079
6            peakrpm           0.015079
13  enginetype_rotor           0.011309
4     cylindernumber           0.008639
0         aspiration           0.008272
7    enginetype_dohc           0.005183
12   enginetype_ohcv           0.000524
1     enginelocation           0.000052
8   enginetype_dohcv                0.0
9       enginetype_l                0.0

In [618]:
threshold = 0.05

weak_features = importance_df[importance_df.feature_importance <= threshold]["feature"].values
weak_features

array(['stroke', 'enginetype_ohcf', 'enginetype_ohc', 'peakrpm',
       'enginetype_rotor', 'cylindernumber', 'aspiration',
       'enginetype_dohc', 'enginetype_ohcv', 'enginelocation',
       'enginetype_dohcv', 'enginetype_l'], dtype=object)

In [646]:
X_strong = df.drop(columns = list(weak_features) + ['price'])
X_strong

model = LogisticRegression()
scores = cross_validate(
    model,
    X_strong,
    y,
    cv=5,
    scoring=['accuracy', 'f1','r2'],
)
scores

{'fit_time': array([0.00829101, 0.0059731 , 0.00449777, 0.00457668, 0.00418639]),
 'score_time': array([0.00894761, 0.00625563, 0.00594163, 0.00813484, 0.00599337]),
 'test_accuracy': array([0.87179487, 0.89473684, 0.94736842, 0.92105263, 0.86842105]),
 'test_f1': array([0.85714286, 0.89473684, 0.95      , 0.91891892, 0.87804878]),
 'test_r2': array([0.48684211, 0.57777778, 0.78947368, 0.68421053, 0.47368421])}

In [641]:
X_strong = df.drop(columns = list(weak_features) + ['price'])
X_strong

model = LogisticRegression()
scores = cross_val_score(
    model,
    X_strong,
    y,
    cv=5
)
strong_model_score = scores.mean()
strong_model_score

0.9006747638326585

🧪 **Kodunu test et**

In [635]:
from nbresult import ChallengeResult

result = ChallengeResult('strong_model',
                         score = strong_model_score
)

result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/mert/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/mert/Sprint-16/S16D2-S-Data-car-prices/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_strong_model.py::TestStrong_model::test_strong_model_score PASSED   [100%]

============================== 1 passed in 0.13s ===============================


💯 You can commit your code:

git add tests/strong_model.pickle

git commit -m 'Completed strong_model step'

git push origin master

## Bonus -  Verilerinizi sınıflandırma (Stratifying your data) ⚖️

💡 Veriyi training ve testing olarak bölerken, dataset’imizdeki kategorik değişkenlerin oranına dikkat etmemiz gerekir — ister target `y`’nin sınıfları olsun ister `X` içindeki kategorik bir feature olsun.

Aşağıda bir örneğe bakalım 👇

❓ Orijinal `X` ve `y` verinizi sklearn’in `train_test_split` fonksiyonunu kullanarak training ve testing olarak ayırın; karşılaştırılabilir sonuçlar elde etmek için `random_state=1` ve `test_size=0.3` kullanın.

In [648]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1)

❓ Training dataset’inizde ve testing dataset’inizde `price` sınıfı **1** olan araçların oranını kontrol edin.

> _Ham `df` içinde bu orana baktığınızda, yaklaşık **%50 / %50** olması gerekir._

In [649]:
print('Training data share of class 1 cars:', y_train.mean())
print('Testing data share of class 1 cars:', y_test.mean())

Training data share of class 1 cars: 0.5037593984962406
Testing data share of class 1 cars: 0.5172413793103449

☝️ Hâlâ yaklaşık olarak **%50 / %50** civarında olmalı.

***Peki random state’i değiştirirsek ne olur?***

❓ `random_state` değerlerini **1’den 10’a** kadar döngüye alın ve her seferinde training ve testing dataset’lerindeki `price` sınıfı **1** olan araçların oranını hesaplayın. ❓

In [653]:
for i in range(1,11):
    print("random_state:",i)
    X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=i)
    print('Training data share of class 1 cars:', round(y_train.mean(),3))
    print('class 1 cars:', y_test.mean())

random_state: 1
Training data share of class 1 cars: 0.504
Testing data share of class 1 cars: 0.5172413793103449
random_state: 2
Training data share of class 1 cars: 0.481
Testing data share of class 1 cars: 0.5689655172413793
random_state: 3
Training data share of class 1 cars: 0.504
Testing data share of class 1 cars: 0.5172413793103449
random_state: 4
Training data share of class 1 cars: 0.534
Testing data share of class 1 cars: 0.4482758620689655
random_state: 5
Training data share of class 1 cars: 0.534
Testing data share of class 1 cars: 0.4482758620689655
random_state: 6
Training data share of class 1 cars: 0.496
Testing data share of class 1 cars: 0.5344827586206896
random_state: 7
Training data share of class 1 cars: 0.534
Testing data share of class 1 cars: 0.4482758620689655
random_state: 8
Training data share of class 1 cars: 0.489
Testing data share of class 1 cars: 0.5517241379310345
random_state: 9
Training data share of class 1 cars: 0.579
Testing data share of class 1 cars: 0.3448275862068966
random_state: 10
Training data share of class 1 cars: 0.489
Testing data share of class 1 cars: 0.5517241379310345

Her seferinde oranların değiştiğini, hatta bazen oldukça ciddi şekilde değiştiğini gözlemleyeceksiniz 😱! Bu durum model performansını etkileyebilir.

❓ `train_test_split(random_state=1)` kullanılarak eğitilen bir Logistic Regression modelinin test skorunu,  
`random_state=9` kullanılarak eğitilen modelin test skoru ile karşılaştırın ❓

Eğitimi training data üzerinde yapmayı ve skoru testing data üzerinde hesaplamayı unutmayın.

In [662]:
model_1 = LogisticRegression()
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1)

model_1.fit(X_train,y_train)
model_1.score(X_test,y_test)

0.9310344827586207

In [663]:
model_9 = LogisticRegression()
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=9)

model_1.fit(X_train,y_train)
model_1.score(X_test,y_test)

0.8103448275862069

👀 `random_state=9` ile çok daha düşük bir skor görmelisiniz; çünkü bu test setindeki sınıf **1** araçların oranı %34.5 iken, training setinde bu oran %57.9’a, hatta orijinal dataset’te yaklaşık %50’ye yakındır.

Bu durum oldukça önemlidir; çünkü dataset’te oluşan bu **rastlantısal dengesizlik**, yalnızca model performansını düşürmekle kalmaz, aynı zamanda eğitim veya değerlendirme sırasında “gerçekliği” de bozabilir 🧐

***Peki bu sorunu nasıl çözebiliriz? Tren seti ve test seti arasında sınıfların dağılımını nasıl aynı tutabiliriz? 🔧***

🎁 Neyse ki sklearn’de, estimator (yani model) bir classifier olduğunda ve target bir sınıf olduğunda, bu durum `cross_validate` tarafından otomatik olarak ele alınır. 📚 [**sklearn.model_selection.cross_validate**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html) dokümantasyonunda `cv` parametresini inceleyin.

Çözüm, aşağıdakini kullanmaktır:

> 📚 [**Stratification (Katmanlama)**](https://scikit-learn.org/stable/modules/cross_validation.html#stratification)

### Hedefin tabakalaşması (Stratification of the target)

💡 ***Stratification*** tekniğini `train_test_split` içinde de kullanabiliriz.

❓ Bu kez **1’den 10’a** kadar olan `random_state` döngüsünü tekrar çalıştırın, ancak bu sefer holdout yöntemine ***`stratify=y`*** parametresini de ekleyin. ❓

In [670]:
for i in range(1,11):
    print("random_state:",i)
    X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=i,stratify=y)
    print("class 1 cars:", round(y_train.mean(),3))
    print("class 1 cars:", round(y_test.mean(),3))

random_state: 1
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 2
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 3
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 4
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 5
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 6
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 7
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 8
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 9
class 1 cars: 0.511
class 1 cars: 0.5
random_state: 10
class 1 cars: 0.511
class 1 cars: 0.5

👀 Random state değişse bile, training ve testing verilerindeki sınıf oranları, orijinal `y` içindeki oranlarla aynı tutulur. İşte _stratification_ (katmanlama) tam olarak budur.

`train_test_split` fonksiyonunu `stratify` parametresiyle kullandığımızda, training ve testing verileri arasında **bir feature’ın oranlarını da koruyabiliriz**. Bu, özellikle aşağıdaki durumlarda son derece önemlidir:

- Churn tahmininde erkek ve kadın müşteri oranlarını korumak 🙋‍♂️ 🙋
- Ev fiyatlarını tahmin ederken büyük ve küçük evlerin oranlarını korumak 🏠 🏰
- Bir sonraki ürünü önerirken 1–5 arası review score dağılımını (multiclass!) korumak 🛍️
- vb.

Örneğin, bizim dataset’imizde `aspiration` feature’ının training ve testing verilerinde aynı oranda kalmasını istiyorsak, şu şekilde yazabiliriz:

`train_test_split(X, y, test_size=0.3, stratify=X.aspiration)`

---

Gördüğümüz gibi, **`cross_validate` [target değişkeni otomatik olarak stratify edebilir](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html#:~:text=For%20int/None%20inputs%2C%20if%20the%20estimator%20is%20a%20classifier%20and%20y%20is%20either%20binary%20or%20multiclass%2C%20StratifiedKFold%20is%20used.)**, ancak **feature’lar için bunu yapmaz** 🤔 Bunun için biraz ekstra çalışmaya ihtiyacımız var.

Bunun için `StratifiedKFold` kullanmamız gerekiyor 🔬

### Tabakalaşma (Stratification - generalized)

📚 [**StratifiedKFold**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html), veriyi `K` parçaya bölerken belirli sütunlar (feature veya target) üzerinden stratification yapmamıza olanak tanır.

Bu sayede, ilgilendiğimiz kategorik feature’ların oranlarını koruyarak manuel bir cross-validation yapabiliriz — bunu ikili (binary) `aspiration` feature’ı ile deneyelim:

In [668]:
from sklearn.model_selection import StratifiedKFold

# Veriyi 5 fold’a bölecek bir stratified k-fold oluşturma
skf = StratifiedKFold(n_splits=5)
scores = []

# .split() metodu bir iterator oluşturur; 'X.aspiration' stratify edeceğimiz feature’dır
for train_indices, test_indices in skf.split(X, X.aspiration):

    # 'train_indices' ve 'test_indices', orantılı bölünmeler üreten indeks listeleridir
    X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
    y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]

    # modeli başlatma ve eğitme
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # en sonunda 5 fold’un ortalamasını almak için skoru listeye ekleme
    scores.append(model.score(X_test, y_test))

np.array(scores).mean()

0.8690958164642375

📚 [**StratifiedKFold**](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html), veriyi `K` parçaya bölerken belirli sütunlar (feature veya target) üzerinden stratification yapmamıza olanak tanır.

Bu sayede, ilgilendiğimiz kategorik feature’ların oranlarını koruyarak manuel bir cross-validation yapabiliriz — bunu ikili (binary) `aspiration` feature’ı ile deneyelim:

🏁 Tebrikler! Tüm veri setini hazırladınız, özellik seçimi yaptınız ve hatta tabakalaşma hakkında bilgi edindiniz 💪.

💾 Not defterinizi git add/commit/push yapmayı unutmayın...

🚀 ... ve bir sonraki challenge'a geçin!